### ISSUE TITLE
Sending Proactive Messages with TurnContextImpl code and documentation are out-of-sync

### ISSUE THREAD

**Issue by untra** [microsoft/botbuilder-java#1007]
## Version
What package version of the SDK are you using:
Preview-6 and on `origin/main`

## Describe the bug
We are using the bot-builder java sdk to send proactive messages to our bot. We are looking through the documentation and trying to setup the turnContext to send a proactive message, given a `channelId` and `serviceUrl` and relevant creds. The documentation and code seem contradictory:

https://docs.microsoft.com/en-us/java/api/com.microsoft.bot.builder.turncontextimpl.turncontextimpl?view=botbuilder-java-preview

https://github.com/microsoft/botbuilder-java/blob/main/libraries/bot-builder/src/main/java/com/microsoft/bot/builder/TurnContextImpl.java#L72-L94

> `withActivity` The incoming activity for the turn; or null for a turn for a proactive message.

However in the code it runs:
```
if (withActivity == null) {
        throw new IllegalArgumentException("activity");
}
```

which means either the logic or the documentation is off...

## To Reproduce
look at code and documentation, one of them is wrong...

## Expected behavior
Do we use TurnContextImpl withActivity set to `null` for a context sending proactive messages? or Don't we?

## Screenshots
n/a

## Additional context
The sdk is a little rough around the edges but its working fairly well for us!

**Comment by tracyboehrer** [comment]
@untra It would appear the docs are off.  Comparing to DotNet, it is the same situation there.  The doc says one thing, but the code throws on a null Activity.

Have you looked at the proactive sample?  It uses continueConversation, which it turn calls ConversationReference.getContinuationActivity to create the Activity. 

As a side note, we are about the release Preview8.  Though this particular issue is there too.

**Comment by untra** [comment]
Thanks for the speedy response and confirming our wonky docs suspicions. `4.6.1-preview8` seems to be working great for us. We got our proactive messages sending now! We used the `createConversation` off of the `botFrameworkAdaptor` to create new conversation threads for our proactive messages. Pardon the kotlin:

```kt
        botFrameworkAdapter.createConversation(
            channelId,
            serviceUrl,
            creds,
            conversationParameters
        ) { context: TurnContext ->
            conversationReference.set(context.activity.conversationReference)
            newActivityId.set(context.activity.id)
            CompletableFuture.completedFuture(null)
        } ...
```

this is working out nicely for us

**Comment by munozemilio** [comment]
@tracyboehrer @untra Im closing this as it seems there is already a resolution. Feel free to re open if needed.
