### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/botbuilder-java#107]
https://github.com/microsoft/botbuilder-java/blob/1dca1dcba045acf1a3e01afe3d457ecf3f146383/libraries/bot-connector/src/main/java/com/microsoft/bot/connector/ConnectorConfiguration.java#L23-L25
The program can potentially fail to release a system resource.

**Comment by tracyboehrer** [comment]
@QiAnXinCodeSafe Thanks!  Fixing now.
