### ISSUE TITLE
Java Bot Framework Release Preview 2 Checklist 

### ISSUE THREAD

**Issue by CoHealer** [microsoft/botbuilder-java#113]
## Change Notes
 

Review all changes that went into 4.6 in the detailed change logs:
[[Change Log for Java](https://github.com/Microsoft/botbuilder-java/issues?utf8=%E2%9C%93&q=is%3Aissue)]   **needs query update**

## GitHub Updates
**Create New Branch** tracyboehrer 
- [x] Java (https://github.com/Microsoft/botbuilder-java/tree/4.6-preview)

**Setup Branch Protection on New Branch** @tracyboehrer 
- [x] Java

**Bump Version on Master** @tracyboehrer 
- [x] Java

**Update Readme.md in master to reflect new branch** @tracyboehrer 

- [x] Java

**Branch Samples** @tracyboehrer 
- [x] Java

**Create DRAFT Release** @CoHealer 
- [X] Java# (https://github.com/microsoft/botbuilder-java/releases/edit/untagged-c969babd26a298e21673)

**Enter release notes and change log** @CoHealer 
- [ ] Java

**Apply Release Notes to DRAFT Release** @CoHealer 
- [ ] Java

**Publish GitHub Release** @tracyboehrer 
- [ ] Java

<a id="testing"></a>
### Testing Status @jwiley84  ###

** Servlet-Echo
- [x] Initializes
- [x] Responds

** Spring-Echo
- [x] Initializes
- [x] Responds

** Emulator
- [x] runs

**(@jwiley84 

**Application Insights**
Currently there is no sample that explicitly demonstrates this. Tested via ngrok to deployed bot
- [ ] Java

**Comment by tracyboehrer** [comment]
@jwiley84 None of the standard samples exist for Java.  The samples are located in the Java SDK tree for now.  There is a Servlet and Spring Boot sample.  There are readme's and ARM templates for both.  Both should deploy to Azure using the instructions in the readme.  The easiest to run locally is the Spring Boot sample.  The Servlet sample would require additional work to run locally (installing and deploying to Tomcat.  Which is why I've only tested via Azure for that).

**Comment by tracyboehrer** [comment]
@CoHealer Its probably a good idea to indicate which packages in the Java SDK are usable.  We will only be publishing the working packages (bot-integration-core, bot-schema, and bot-connector).  But the GitHub repos will contain packages in various stages of completion (most are empty).  We don't want people wasting time with packages that aren't usable (bot-builder and bot-dialog namely).

**Comment by CoHealer** [comment]
Ack, I'll direct users to the three working packages and caution them that the others are not yet ready.
