### ISSUE TITLE
Did not deploy bot-java parent POM

### ISSUE THREAD

**Issue by michaelboyles** [microsoft/botbuilder-java#120]
You did not deploy the parent POM to [Maven Central](https://search.maven.org/search?q=com.microsoft.bot), so adding a dependency upon any child module will fail because it cannot resolve the parent.

See https://stackoverflow.com/questions/58131603/what-is-the-way-to-get-bot-java-lib-from-maven-central

**Comment by jwiley84** [comment]
@tracyboehrer for ping.

**Comment by tracyboehrer** [comment]
@michaelboyles Thanks for the heads up, Michael.  My bad.  I published the parent POM and verified I could build the samples.  You should be good to go without the work-around of manually putting it in your local cache.

**Comment by michaelboyles** [comment]
Sure, no problem. Thanks for responding so quickly.

I've tested and verified. The HTML index of maven central hasn't updated -- I guess it's cached for a while -- but I'm able to build successfully.
