### ISSUE TITLE
Maven Dependency Error for bot-connector and bot-schema version 4.0.0-SNAPSHOT?

### ISSUE THREAD

**Issue by HaoyiZhao** [microsoft/botbuilder-java#122]
Hello, I'm in the process of updating a bot that was already created, however I am receiving the following maven errors when attempting to compile the bot before making any changes:

`Failure to find com.microsoft.bot.connector:bot-connector:pom:4.0.0-SNAPSHOT in https://botbuilder.myget.org/F/botbuilder-v4-java-daily/maven/ was cached in the local repository
Failure to find com.microsoft.bot.schema:botbuilder-schema:pom:4.0.0-SNAPSHOT in https://botbuilder.myget.org/F/botbuilder-v4-java-daily/maven/ was cached in the local repository`

I tried going through the version history of the two dependencies but I could not find the specified version (4.0.0-SNAPSHOT) there either. The existing bot library works by itself as a jar however so it seems that the dependency versions did exist at a certain point. It appears as though the previous dependency versions no longer exist currently? I'm not sure if I should just try to find a working stable version of the dependencies and use that instead or maybe the existing dependency version can still be found somewhere?

**Comment by tracyboehrer** [comment]
Are you doing a Maven build of the Java SDK, or just a sample?

The POM's on GitHub have the default 4.0.0-SNAPSHOT version and don't actually exist anywhere.  If you are trying to build just a sample from the code on GitHub, update the bot-* dependencies to 4.6.0-preview2 in the sampes pom.xml.

Alternatively, you could do a "mvn install" from the root Java SDK dir, which will install the 4.0.0-SNAPSHOT packages in your local cache.  Then from a sample dir, do a "mvn package".  At that point, the samples will be able to find the 4.0.0-SNAPHOTS packages.

Does that make sense?

**Comment by HaoyiZhao** [comment]
I was just using a sample. Thanks for the information, I think I understand what needs to be done now.
