### ISSUE TITLE
Teams not being able to render an OAuth card 

### ISSUE THREAD

**Issue by ldardick** [microsoft/botbuilder-java#1300]
## Version
4.13.0

## Describe the bug
Both Web Chat and Bot Framework Emulator are able to render an OAuth card generated by the SDK, while Teams is not.
This is not limited to Java as I tested the C# SDK with the same result. 

## To Reproduce
1. Use the [Teams Auth (#46) sample](https://github.com/southworks/BotBuilder-Samples/tree/main/samples/java_springboot/46.teams-auth)
2. Configure the Bot on Azure with an OAuth connection according to [this document](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=java%2Caadv2#azure-ad-identity-service)
3. Follow the instructions in the [sample README file](https://github.com/southworks/BotBuilder-Samples/blob/main/samples/java_springboot/46.teams-auth/README.md) 
4. Run the sample locally and configure the `ngrok` tunnel
5. Upload the App on Teams (Either Web Client or the Native App)
5. Verify how the bot succeeds on sending the welcome message but fails to render the OAuth card

## Expected behavior
Teams is expected to render an OAuth card enabling the user to authenticate with the OAuth provider

## Screenshots
N/A

## Additional context
I put a breakpoint and captured the Login URL that is intended to be displayed on the button of the card. Opening this URL in the browser I could continue the authentication flow normally even though the card is not displayed

![image](https://user-images.githubusercontent.com/58704965/127912226-12ec8249-022e-4c7a-9124-71244d9ab2be.png)

I also tried to create the card manually by copying [this snippet](https://github.com/microsoft/botbuilder-java/blob/aef69689a519739fa0f6e8108f19fcf08222a74c/libraries/bot-dialogs/src/main/java/com/microsoft/bot/dialogs/prompts/OAuthPrompt.java#L200-L230) so it's rendered after the welcome message without any interaction from the user, followed by a statement, and verified that its rendered on Web Chat and not on Teams

![image](https://user-images.githubusercontent.com/58704965/127912599-372f86d6-7ec2-490a-8b99-e2fcae6513da.png)

![image](https://user-images.githubusercontent.com/58704965/127912631-8222c421-72eb-494d-a5b6-4adacac41c35.png)

**Comment by stevkan** [comment]
@ldardick, unfortunately, I am unable to repro the issue. Testing the sample using the 4.13.0 version of the SDK renders the OAuth prompt every time for me in Teams.

That being said, could you verify you are using an updated copy of the sample? A bug was identified in the sample just prior to the release of the SDK that was resulting in the card not displaying.

**Comment by ldardick** [comment]
@stevkan I can confirm I'm using the latest version from master (Using the SDK 4.13.0 in Java and 4.14.1 in C#).
I tested this once again with the same result (Working in Web Chat but not in Teams).

Please let me know if you want me to provide any additional information that can be use to reproduce the issue or even if you prefer to jump into a quick call so we can review this together.

**Comment by tracyboehrer** [comment]
To clarify... The latest Java version is 4.14.0. What is in master is actually 4.15.0-SNAPSHOT.  Though it should be very close to what is in the 4.14 branch.

Does this happen using the 4.14.0 packages from Maven?

**Comment by ldardick** [comment]
@tracyboehrer I tested this with the latest version from **BotBuilder-Samples**, which is using `4.13.0`. However, I'll try once again using `4.14.0` to verify this.

**Comment by ldardick** [comment]
My bad, I thought that `BotBuilder-Samples` was using `4.13.0` when [it's actually using `4.14.0`.](https://github.com/microsoft/BotBuilder-Samples/blob/de6e7a756ab78755b9976d1f9ee95e578acb71f6/samples/java_springboot/46.teams-auth/pom.xml#L98-L109). Nevertheless, I just checked that it also happens modifying the sample to use `4.13.0`.

**Comment by LeeParrishMSFT** [comment]
I'm taking off the customer reported tag, this was reported during internal testing by the Southworks team and doesn't need to be tracked as a customer reported issue.

**Comment by stevkan** [comment]
@LeeParrishMSFT, could you please assign an owner for this? I'm not sure who that should be...if that is someone from Southworks or another. Thanks!

**Comment by LeeParrishMSFT** [comment]
@stevkan I'll assign it to myself since I'd like to run some tests and see what I can find since you didn't see this in 4.13 and yet ldardick said they did. I remember verifying the Teams Auth sample in 4.13 and don't remember seeing any problems, so it has me curious.

**Comment by stevkan** [comment]
@LeeParrishMSFT, if I can be of help, let me know!

**Comment by LeeParrishMSFT** [comment]
I just verified that it works with 4.14 and 4.13 as expected within Teams, the Auth card is shown as expected. My thought is that the Readme.md file is not explicit enough about requiring the step to add authentication to the bot here: [Add authentication to a bot](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=csharp) and as such if this step isn't completed the sample doesn't work. This step is just show in the Further Reading section and not called out that it must be performed. I'll make a modification to the Readme.md file in the Samples repo to make this more explicit. Tracking this through this issue in the samples repo: [Java Sample 46.Teams-Auth documentation missing required step](https://github.com/microsoft/BotBuilder-Samples/issues/3405)
