### ISSUE TITLE
Microsoft Teams bot App not working when configured for single tenant

### ISSUE THREAD

**Issue by gaurav2493** [microsoft/botbuilder-java#1323]
## Version
  bot-integration-spring: 4.14.0
  java: 11
  
  ## Describe the bug
When botFrameworkAdapter is created for single tenant Microsoft Teams Bot, the bot does not work. API calls fails with error:

    com.microsoft.aad.msal4j.MsalServiceException: AADSTS700016: Application with identifier '95440f48-b68f-4f3b-8906-9e94dae0968a' was not found in the directory 'Bot Framework'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant.
    Trace ID: 1f757835-358a-443a-8dfa-5c98c5fe1200
    Correlation ID: a1af3322-0960-4dff-9424-c96161f0a11c
    Timestamp: 2021-09-26 11:06:02Z

The whole process works if app is changed from single tenant to multi-tenant.(In Azure portal -> app registration -> app -> manifest, the value of key `signInAudience` is changed to `AzureADandPersonalMicrosoftAccount` or `AzureADMultipleOrgs`​​​​​​)

 We want to make the app to work only on our tenant, but this is currently failing
  
  ## To Reproduce
 Please follow the following steps:
1. Clone the sample project and setup as instructions provided in Readme.md
2. In Azure portal -> app registration -> app -> manifest, set the value in key `signInAudience` to `AzureADMyOrg`​​​​​​ 
3. Send a message to the app and the bot will not respond. Some errors can be seen in the console.

  ## Expected behavior
  The bot should respond to messages, but it does not.

  ## Tracking Status
  
  **Java SDK** [TODO]()
  - [ ] PR
  - [ ] Merged

**Comment by LeeParrishMSFT** [comment]
@gaurav2493  The bot's app registration must be set to one of the multi-tenant options (AzureADandPersonalMicrosoftAccount or AzureADMultipleOrgs) and not AzureADMyOrg. The reason for this is the bot needs to be able to access the BotFramework connector services (i.e., the channels able to be configured in your bot's Azure settings, which includes the Teams channel) which are not in your org. If not set to multi-tenant, then the bot will fail.
