### ISSUE TITLE
Activity loses it's properties onTurnError

### ISSUE THREAD

**Issue by esfomeado** [microsoft/botbuilder-java#1469]
## Version
What package version of the SDK are you using.
4.14.2

## Describe the bug
```
final Activity activity = MessageFactory.text( "Test" );
activity.setProperties( "key", JsonNodeFactory.instance.textNode( "test" ) );

...
setOnTurnError( ( turnContext, exception ) -> {
    final Activity activity = turnContext.getActivity();

    LoggerFactory.getLogger( AdapterWithErrorHandler.class ).error( "onTurnError", exception );

    System.out.println( exception );

    return null;
} );
```

If I create an activity and give it a property on the `onTurnError` this property is no longer present.

If I put the same property inside the Conversation, the value isn't lost.

## To Reproduce
See example above.

## Expected behavior
The activity properties should be present

**Comment by ramfattah** [comment]
Hello @esfomeado, I'm investigating this issue.

**Comment by esfomeado** [comment]
If you need more info just let me know

**Comment by ramfattah** [comment]
Thanks, @esfomeado, are you able to share a minimal reproducible sample?

**Comment by esfomeado** [comment]
@ramfattah Sample here:

https://github.com/esfomeado/botbuilder-sample

**Comment by ramfattah** [comment]
Thanks for sending a reproducible sample.
Investigating further.

**Comment by ramfattah** [comment]
Hey @esfomeado 

Can you please share the steps to run the sample on local machine? 

#

Looks like the shared repro sample is built with Gradle and the steps to run the project seem to be different found in [/java_springboot/](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot) samples.

For example, here are the steps I took to attempt to run the project:
1. Built the project, this generated a build folder containing `.jar` file
     * Video demo: https://i.gyazo.com/5354ce867450782eca85fe582a3fb27e.mp4
2. Ran the command ` java -jar path-to-newGenerated-jar `
     * Got error "no main manifest attribute"
     * Video demo: https://i.gyazo.com/8d16a9bbca95f29956d9723797d4acea.mp4

**Comment by ramfattah** [comment]
Hey @esfomeado 

Can you please share the steps to run the reproducible sample on local machine? 

#

Looks like the shared repro sample is built with Gradle and the steps to run the project seem to be different found in [/java_springboot/](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot) samples.

For example, here are the steps I took to attempt to run the project:
1. Built the project, this generated a build folder containing `.jar` file
     * Video demo: https://i.gyazo.com/5354ce867450782eca85fe582a3fb27e.mp4
2. Ran the command ` java -jar path-to-newGenerated-jar `
     * Got error "no main manifest attribute"
     * Video demo: https://i.gyazo.com/8d16a9bbca95f29956d9723797d4acea.mp4

**Comment by esfomeado** [comment]
You can just run it via Intellij. Just press the green arrow on the main on `Application.java`

**Comment by ramfattah** [comment]
Hi @esfomeado 

Thanks for the prompt response.

After pressing the green arrow on `Application.java`, looks like it started server on port 9999?
![image](https://user-images.githubusercontent.com/38049078/171675798-a9446526-b53b-48dd-842a-b7395bccd7c9.png)


In emulator, I provided the Bot URL as `http://localhost:9999/api/messages/`
![image](https://user-images.githubusercontent.com/38049078/171676108-ac69a244-d3da-40a8-8ec1-c19b0d8549d1.png)


And got the following error:
![image](https://user-images.githubusercontent.com/38049078/171676159-9483df65-0f3a-4067-a651-eaeacf22703b.png)

**Comment by esfomeado** [comment]
That's the idea to trigger the error handler. If you put a breakpoint on the error handler where I get the activity you Will see that the activity does not have any property

**Comment by gabog** [comment]
Hi, from looking at your sample, `turnContext.getActivity();` will return the activity the bot received and it will not have the property you are setting in `activity.setProperties( "key", JsonNodeFactory.instance.textNode( "test" ) );` that property will be only present on the activity going out. If you need that in the error handler you'll probably need to store that somewhere else (like conversation maybe) and access that value in the error handler. 

Hope this helps

**Comment by esfomeado** [comment]
Sure but it's confusing since the Activity that I get on the error handler is the one received but contains the conversation going out.

To be honest this does not make any sense. It should contain the activity going out as well.

**Comment by gabog** [comment]
The conversation object in the conversation property of the activity will be also be updated on the way out by the underlying framework infrastructure.
