### ISSUE TITLE
Error When Trigger Action.Execute From Adaptive Card in Teams Message

### ISSUE THREAD

**Issue by johnmiroki** [microsoft/botbuilder-java#1477]
## Version
What package version of the SDK are you using.
4.14.2
Spring Boot 2.7.1

## Describe the bug
Give a clear and concise description of what the bug is.
When a button with "Action.Execute" is clicked, the request sends to Bot SDK. When SDK is reading the "value" from activity, it asumes it's a JsonNode, but in fact, it's LinkedHashMap, hence it sends error to Teams

see `node = (JsonNode) obj;` starting line 705 of ActivityHandler
```Java
        Object obj = activity.getValue();
        JsonNode node = null;
        if (obj instanceof JsonNode) {
            node = (JsonNode) obj;
        } else {
            AdaptiveCardInvokeResponse response = createAdaptiveCardInvokeErrorResponse(
                HttpURLConnection.HTTP_BAD_REQUEST, "BadRequest", "Value property instanceof not properly formed");
            throw new InvokeResponseException(HttpURLConnection.HTTP_BAD_REQUEST, response);
        }
```

## To Reproduce
1. Send an adaptive card to message, with action:
```json
    {
      "type": "Action.Execute",
      "title": "Update Card",
      "id": "updateCard"
    }
```
2. Click on the button "Update Card"
3. Teams client gets response: `{"errorCode":1008,"message":"<BotError>Bot returned unsuccessful status code BadRequest"}`
4. An error shows up "Unable to reach app. Please try again."
5. No error logging in the backend

## Expected behavior
Backend processes activity.getValue() as LinkedHashMap or whatever it could be (depending on the code deserializing activity json)

## Additional context
If I somehow convert activity.value into JsonNode, everything works.
Two ways:
1. Write a class extends BotController, and after Activity is passed in as controller parameter, substitute actitivy.value with a JsonNode `activity.setValue(new ObjectMapper().convert(activity.getValue(), JsonNode.class))`
2. Write a class replacing the default BotController, where specifies Jackson to treat value as JsonNode
```java
  private static class SFActivity extends Activity {
    @JsonDeserialize(as = JsonNode.class)
    @JsonProperty("value")
    private Object value;

    @Override
    public Object getValue() {
      return value;
    }

    @Override
    public void setValue(Object value) {
      this.value = value;
    }
  }
```

**Comment by stevkan** [comment]
@johnmiroki, your assessment seems to be on point. We are deciding what the next steps should be and will respond once that has been decided.

**Comment by johnmiroki** [comment]
@stevkan Thank you for your confirmation!
