### ISSUE TITLE
Adaptive Card Support Enhancement: Templating And i18n

### ISSUE THREAD

**Issue by johnmiroki** [microsoft/botbuilder-java#1479]
### Use this [query](https://github.com/microsoft/botbuilder-java/issues?q=is%3Aissue+is%3Aopen++label%3Afeature-request+) to search for the most popular feature requests.

**Is your feature request related to a problem? Please describe.**
C# and Nodejs SDK both have support from adaptive card templating, ie using variables in the adaptive card and "expanding" it with values. However, there's no such support in Java.
Another related feature is i18n, for enterprise grade app, i18n is a must. However, without native support and with Templating missing, it's hard to implement i18n.

**Describe the solution you'd like**
Port Adaptive Card Templating from C#/Node to Java SDK

**Describe alternatives you've considered**
Considering to try Thymeleaf or other templating engine as an interim solution

**Additional context**

**Comment by tracyboehrer** [comment]
Java SDK entered sustained engineering and will be retired November 2023.  New features will not be added during this time.  We will continue to support existing bots via critical bug fixes and security updates.

**Comment by johnmiroki** [comment]
@tracyboehrer Thanks for the update. Thought I'm sorry for the MS's decision to discontinue the SDK. Java Ecosystem is thriving. Do you happen to have the official roadmap? We need to reevaluate our investment in the SDK. Much appreciated!
