### ISSUE TITLE
[OAuthPrompt] The call to https://api.botframework.com/api/usertoken/GetToken returns a 500 response

### ISSUE THREAD

**Issue by pastox** [microsoft/botbuilder-java#1490]
## Version
4.14.1

## Describe the bug
I've been trying to use the bot samples in java, especially the [bot-authentication](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/18.bot-authentication) one, which uses the SDK version 4.14.1

When using the OAuthPrompt Dialog from the SDK, the call to https://api.botframework.com/api/usertoken/GetToken performed by the SDK returns a 500 status error response. According to the code, the SDK awaits either a 200 or 404 status.
This is probably an issue with the api but I'm posting here.

## To Reproduce
1. Follow the instructions at https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=multitenant%2Caadv2%2Cjava
2. Test the bot-authentication sample
3. You should see the prompt `Welcome to AuthenticationBot. Type anything to get logged in. Type 'logout' to sign-out.`
4. Type anything except `logout`
5. The Auth Prompt should appear but nothing happens
6. Start again with the debugger active with a breakpoint at `com.microsoft.bot.connector.rest.RestUserToken` on the first line of the 
method `ServiceResponse<TokenResponse> getTokenDelegate(Response<ResponseBody> response)`
7. Observe a 500 status in the response with the error body
```bash
{
  "error": {
    "code": "ServiceError",
    "message": "Error retrieving token: 59966167e635c640bc5061aa7a2084ba."
  }
}
``` 
Maybe I configured my Azure resources badly, but at least I would expect a client error status

## Expected behavior
The API returns 404 and the Oauth prompt shows on the chat

**Comment by ramfattah** [comment]
Hi @pastox,

I was not able to reproduce this issue using java bot sample [18.bot-authentication](https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/csharp_dotnetcore/18.bot-authentication).

![image](https://user-images.githubusercontent.com/38049078/193884695-54e1a3d1-055b-4d30-a9d3-5c044f608322.png)

Followed the [Create the Azure AD identity provider](https://learn.microsoft.com/en-us/azure/bot-service/bot-builder-authentication?view=azure-bot-service-4.0&tabs=multitenant%2Caadv2%2Cjava#create-the-azure-ad-identity-provider) documentation to authenticate the bot.

**Comment by ramfattah** [comment]
Hi @pastox, any updates on this?

**Comment by pastox** [comment]
Hello @ramfattah 
thank you for your answer.
Another colleague of mine tried to follow the same steps and reproduced the issue.

So we think it might be a problem related to our Azure organization/subscription. Do you know of any configuration differences in the Azure accounts/permissions/subscriptions that could cause such issues ?

Thank you in advance.

**Comment by ramfattah** [comment]
Hi @pastox,

* What app type (notes in [Plan your deployment](https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp#plan-your-deployment) and [Bot identity information](https://learn.microsoft.com/en-us/azure/bot-service/provision-and-publish-a-bot?view=azure-bot-service-4.0&tabs=userassigned%2Ccsharp#bot-identity-information)) is the Azure Bot resource using?
* Are you able to test the OAuth connection successfully in Azure Portal?
      ![image](https://user-images.githubusercontent.com/38049078/198417890-e1ebbf4c-2e7a-4cdc-8df6-7ed82969e09e.png)

**Comment by ramfattah** [comment]
Closing due Inactivity. @pastox please re-open if needed.
