### ISSUE TITLE
Echo bot sample returns error when using LINE channel

### ISSUE THREAD

**Issue by MinoMinoMinoru** [microsoft/botbuilder-java#1514]
# Sample information
- Sample type: Java SDK Echo Bot Sample
https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/02.echo-bot
- Sample language: Java
- Channel : LINE Channel (other than LINE channel, Web Chat and Teams channels are enabled and the issue only occurs when using LINE channel

# Describe the bug
When using Java SDK Echo Bot Sample, the bot sends payload like below
> "conversation":{"properties":{},"isGroup":false,"id":"xxxxxxxxxxxxxxxxxxxxxxxx"}

and having this "properties" was causing LINE channel to return 400 error.
*The LINE connector does not return 400 error as of now because the Bot Service rolled back to the previous state which did not return 400 error.

Same payload is sent to Web Chat as well but only LINE channel returned errors and responses from Web Chat channel were fine.
 
# To Reproduce
Go to https://github.com/microsoft/BotBuilder-Samples/tree/main/samples/java_springboot/02.echo-bot and enable LINE Channel.
※Make sure "properties":{} is included

# Expected behavior
Since "properties" seems unnecessary, eliminate it so it would not cause 400 error even if the Bot Service rolls out the change.

**Comment by dmvtech** [comment]
@MinoMinoMinoru Are you still experiencing this issue?

**Comment by dmvtech** [comment]
Closing due to lack of response.
