### ISSUE TITLE
Update Road Map

### ISSUE THREAD

**Issue by mslinn** [microsoft/botbuilder-java#153]
The [road map](https://github.com/Microsoft/botbuilder-java/wiki/Roadmap) is a year out of date (last milestone mentioned is for Dec 2018).

**Comment by sgellock** [comment]
@mslinn, thanks for opening the issue.  The team is working to update our collective roadmaps before the end of the year.  We'll include our Java roadmap as part of that refresh.  For now, the currently available preview release is what we'll have through the end of calendar year 2019.  The earliest for our next update would be our R8 release, which is March 16th (+/-).

**Comment by christopheranderson** [comment]
Java roadmap is here: https://github.com/microsoft/botframework-sdk/wiki/Roadmap#java-preview

Our engineering investments will likely be relatively light until we've gathered some more feedback or customer demand. Given that, the roadmap is also pretty sparse until we've gotten more info.
