### ISSUE TITLE
[PORT] add TestFlow.AssertNoReply and tests

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-java#155]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3125

To make sure the bot really ends.
Unexpected replies once happend in VA-Skill interactions in solutions project.

**Comment by LeeParrishMSFT** [comment]
There are no tests that use these method, so they can be ported if we ever add a test that requires them in the future.
