### ISSUE TITLE
Customizations package

### ISSUE THREAD

**Issue by wmeints** [Microsoft/botbuilder-java#16]
There's a `customizations` package in the bot-connector library that I don't get name-wise. Is this meant to stay this way, do we get a better package structure? Right now it contains everything including a kitchen sink.

I think it has to do with the AutoRest code generation process, but I'm unsure.

**Comment by daveta** [comment]
Hi Willem,
Another good find.  Digging in and hopefully getting rid of that package..  Again, will ping when it's done.
Thanks, -Dave

**Comment by daveta** [comment]
Hi Willem,
You're spot on - apparently "customizations" is the non-generated code, the other stuff is generated.  
Thanks, -Dave

**Comment by daveta** [comment]
Hi Willem,
FYI: Hopefully by end of this week, will update package to push alot of this stuff into authentication to make it more consistent with C# and other libraries..
Thanks, -Dave
