### ISSUE TITLE
[PORT] Update BotAdapter (for skills / adapters compat)

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-java#166]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3148

#3147  - Added additional ContinueConversationAsync overload for custom adapters for skills compatibility.
#3146 - Move 'BotIdentityKey' const to BotAdapter and made it public.

**Comment by garypretty** [comment]
Custom adapters do not currently exist for Java - just requires move 'BotIdentityKey' const to BotAdapter and made it public for parity.
