### ISSUE TITLE
Echo Bot example doesn't compile with Maven

### ISSUE THREAD

**Issue by joao-parana** [microsoft/botbuilder-java#171]
## Version

Version of the SDK :  **4.6.0-preview3**

## Describe the bug

The Echo Bot example doesn't compile

## To Reproduce

Steps to reproduce the behaviour:

1. Go to root folder for `echo-bot` sample (See: https://github.com/microsoft/botbuilder-java/blob/master/samples/02.echo-bot)
2. run `mvn compile`
3. See the log
4. See the error

## Expected behavior

Compile must be run without problem with Maven

## The Bug

The dependency node on pom.xml for bot-integration-spring is wrong.

```xml
      <dependency>
        <groupId>com.microsoft.bot</groupId>
        <artifactId>bot-integration-spring</artifactId>
        <version>4.0.0-SNAPSHOT</version>
        <scope>compile</scope>
      </dependency>
```

Correct value for version is:

```xml
    <version>4.6.0-preview3</version>
```

**Comment by joao-parana** [comment]
The same error occur with others samples on https://github.com/microsoft/botbuilder-java/tree/master/samples

**Comment by tracyboehrer** [comment]
@joao-parana Thanks!  Another options is to "mvn install" from the project SDK root.  This will get the packages in your local cache.  I will look into a solution for those that just want to run the samples.  Down the road, when we move the Java samples to the botbuilder-samples repo, we'll change the dependencies to the release version.

**Comment by shahamit** [comment]
@tracyboehrer - I was stuck with the same issue but thanks to your comment. 'mvn install' gets the work done.

**Comment by kos811** [comment]
For me worked next way:
in this repo there is all needed dependencies, that needed too build samples.

so, you just need to "install (mvn install)" maven projects in your local repo (in windows:C:\Users\<your username>\.m2\repository) in next sequention:
- bot-schema
- bot-connector
- bot-builder (Transcript_TestDateLogUpdateActivities tests fails, i commented it)
- bot-integration-core
- bot-integration-spring
