### ISSUE TITLE
too many jars and dependencies. am i missing something here. 

### ISSUE THREAD

**Issue by ashwinbiyani** [Microsoft/botbuilder-java#23]
I have downloaded close to 20-25 jars so far to resolve no class def found error, still, it is continuously throwing errors one after another. Am I the only one who is facing? anyone else?

**Comment by daveta** [comment]
At the moment, we're currently building three jars for schema, connector and botbuilder.  I'm not sure where it was when this was filed, but we're in-sync with the dotnet.

**Comment by ashwinbiyani** [comment]
I tried doing maven build and it was failing so, i started adding jars
manually one by one. Resolving dependencies took a while.

I was all set back then. Please close this.
