### ISSUE TITLE
[PORT] Create test for waterfall cancellation telemetry

### ISSUE THREAD

**Issue by tomlm** [microsoft/botbuilder-java#244]
> Port this change from botbuilder-dotnet/master branch:
https://github.com/microsoft/botbuilder-dotnet/pull/3314

For https://github.com/microsoft/botbuilder-js/issues/1619

# Changed projects
* Microsoft.Bot.Builder.Dialogs.Tests

**Comment by v-kydela** [comment]
@tomlm - There are no waterfalls in Java. Should this be closed?

**Comment by tracyboehrer** [comment]
These are automated issues based off changes to C#. I will go through them at some point and close all those that don't apply.

________________________________
