### ISSUE TITLE
Package on maven central cannot be used

### ISSUE THREAD

**Issue by wmeints** [Microsoft/botbuilder-java#30]
I tried to use the package as it is published on maven central, but it refers to the bot-parent POM which is not published on maven central. 

```
Failed to read artifact descriptor for com.microsoft.bot.connector:bot-connector:jar:4.0.0-a0: Could not find artifact com.microsoft.bot:bot-parent:pom:4.0.0-a0 in central
```

The only way to get around it is to download the sources from github and run `mvn install` on them.

**Comment by daveta** [comment]
Hi Willem,
Thanks for your report.  I'm filing an issue so we can track and resolve.  You're workaround is good, but we'll publish out a new one hopefully next week.  I'll ping you when it's up there.
Thanks, -Dave

**Comment by daveta** [comment]
Hi Willem,
Can you give it a shot?  Thanks! -Dave

**Comment by matthub** [comment]
Just to confirm: using version `4.0.0-a1` worked for me without the workaround, Thanks!
