### ISSUE TITLE
Interesting implementation of a standard class in Java

### ISSUE THREAD

**Issue by wmeints** [Microsoft/botbuilder-java#33]
Saw that people are working on the middleware stuff. Great work, can't wait to use it. 
While browsing the code, I saw an interesting implementation of `Func`

https://github.com/Microsoft/botbuilder-java/blob/e6f87b42ecf42c212a94a11cf9e24e9adc58bbb2/libraries/botbuilder/src/main/java/com/microsoft/bot/builder/core/Func.java#L3-L6

It looks very similar to [Consumer](https://docs.oracle.com/javase/8/docs/api/java/util/function/Consumer.html). Is it intentional to recreate it as a `Func` class?

**Comment by daveta** [comment]
Hi Willem, 
Great observation, i'm redoing this to actually use Callable<> so I can throw exceptions.  I was toying with a bunch of functional interfaces for unique exception throwing, but just settled on Callable<>..  Curious if you had any thoughts.
Thanks! -Dave
