### ISSUE TITLE
Teams Channel SuggestedActions  no show

### ISSUE THREAD

**Issue by chineseqw** [microsoft/botbuilder-java#387]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]
Teams Channel SuggestedActions  no show

**Comment by v-kydela** [comment]
Hi @chineseqw 

You can see [here](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channels-reference#action-support-by-channel) that Microsoft Teams does indeed not support suggested actions. I'm closing this issue now.
