### ISSUE TITLE
Extension message : 50.teams-messaging-extensions-search no run like in nodejs.

### ISSUE THREAD

**Issue by Appkad** [microsoft/botbuilder-java#415]
## Version
v2.1.7.RELEASE

## Describe the bug
no list after search forms teasm

## To Reproduce
1. Go to Teams
2. Click on icon correpondint at my apps 
3. Windows Search opening
4. Write one word ou anything

## Expected behavior
no error in java ide.
error fomr teams : Unable to reach app. Please try again.

## Screenshots
![image](https://user-images.githubusercontent.com/25465376/78791287-f8e1b280-79af-11ea-81e6-0f1d182de791.png)

## Additional context
I test the same in nodejs, it's ok.
[bug]

**Comment by cleemullins** [comment]
@Appkad We're adding Teams Support to Java this iteration (R9). It's currently in development, and is scheduled to ship in Mid-May. 

For now, our Teams support is limited to our Python, C#, and JavaScript SDKs.

**Comment by Appkad** [comment]
Hello,

I was able to recover the message extension as soon as it was available.
I had another question, I opened another ticket.
Thank you

Best regards,
