### ISSUE TITLE
SuggestedActions not working for me

### ISSUE THREAD

**Issue by DanielFedo** [Microsoft/botbuilder-java#44]
Hello, 
I can't seem to make SuggestedActions work.
This is my code:

```
SuggestedActions suggestedActions = new SuggestedActions()
        .withActions(
            new ImmutableList.Builder<CardAction>()
                    .add(new CardAction().withType(ActionTypes.IM_BACK).withValue("hello").withTitle("Hello"))
                    .add(new CardAction().withType(ActionTypes.IM_BACK).withValue("byebye").withTitle("Byebye"))
                    .build()
        )
        .withTo(
                new ImmutableList.Builder<String>().add(user.id()).build()
        );

Activity newActivity = new Activity()
        .withType(ActivityTypes.MESSAGE)
        .withText("Choose an action")
        .withRecipient(user)
        .withFrom(bot)
        .withInputHint(InputHints.EXPECTING_INPUT)
        .withSuggestedActions(suggestedActions);

client.conversations().sendToConversation(conversationId, newActivity);
```
The user gets the message, but the quick reply buttons don't appear (Tested with MicrosoftTeams).

Thanks

**Comment by daveta** [comment]
fyi: i'm checking into this..

**Comment by daveta** [comment]
Here's a tool to understand what features are supported under what channel.  My understanding is this reflects a snapshot of what was supported several months ago, but according to this tool, SuggestedActions aren't supported under Microsoft Teams yet.

https://docs.botframework.com/en-us/channel-inspector/channels/Teams?f=SuggestedActions&e=example1

Thanks
