### ISSUE TITLE
Maven tests fail to compile out-of-the-box

### ISSUE THREAD

**Issue by roalexan** [Microsoft/botbuilder-java#53]
Following steps here - https://github.com/Microsoft/botbuilder-java/wiki/building-the-sdk. 

skipping tests as follows works: mvn package -Dmaven.test.skip=true
but running as-is with tests doesn't: mvn package --log-file log.txt

log.txt attached. [log.txt](https://github.com/Microsoft/botbuilder-java/files/2215305/log.txt)

My environment:

git --version
	git version 2.13.3.windows.1
java -version
	java version "10.0.1" 2018-04-17
	Java(TM) SE Runtime Environment 18.3 (build 10.0.1+10)
	Java HotSpot(TM) 64-Bit Server VM 18.3 (build 10.0.1+10, mixed mode)
mvn -version
	Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T14:33:14-04:00)
	Maven home: C:\maven\apache-maven-3.5.4-bin\apache-maven-3.5.4\bin\..
	Java version: 10.0.1, vendor: Oracle Corporation, runtime: C:\Program Files\Java\jdk-10.0.1
	Default locale: en_US, platform encoding: Cp1252
	OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"

Build steps:

	cd c:\microsoft\repos
	git clone https://github.com/Microsoft/botbuilder-java.git
	cd botbuilder-java
	mvn package

Compilation errors:

[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /C:/microsoft/repos/botbuilder-java/libraries/botbuilder/src/test/java/com/microsoft/bot/builder/BotStateTest.java:[376,48] incompatible types: java.lang.Object cannot be converted to com.microsoft.bot.builder.CustomState
[ERROR] /C:/microsoft/repos/botbuilder-java/libraries/botbuilder/src/test/java/com/microsoft/bot/builder/BotStateTest.java:[397,48] incompatible types: java.lang.Object cannot be converted to com.microsoft.bot.builder.CustomState
...

**Comment by daveta** [comment]
This was fixed.  Please reopen if you still have problems.
