### ISSUE TITLE
New version full like Python, C#

### ISSUE THREAD

**Issue by Appkad** [microsoft/botbuilder-java#545]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]
Hello,
Can you tell me when the Java version will be available?
Otherwise the 18.bot-authentication project will be available please?

Best regards,

Kader.

**Comment by benbrown** [comment]
We don't have a timeframe for the release of Java, but development continues.

**Comment by benbrown** [comment]
@tracyboehrer can you leave an update on the ETA for sample 18?

**Comment by tracyboehrer** [comment]
@Appkad Sample #18 has a reliance on some dependencies that haven't been developed yet.  The big one is the dialog stack, for which we don't have a hard ETA on yet.  In theory, the OAuth flow could be done without the dialog stack (primarily the flow in the OAuthPrompt from C#).  Most of that functionality is in the BotAdapter and would have to be tied together in the bot.  With that said, there are a couple things missing there, so the complete range of situations that C# handles could not be accomplished yet.
