### ISSUE TITLE
Zone Editor Disappear

### ISSUE THREAD

**Issue by Appkad** [microsoft/botbuilder-java#577]
🚨 The issue tracker is not for questions 🚨

If you have a question, please ask it on https://stackoverflow.com/questions/tagged/botframework

[question]
Why the zone disappear after deploy App ?
![image](https://user-images.githubusercontent.com/25465376/83501254-2afb2680-a4c0-11ea-952f-e3efa7608258.png)

**Comment by stevkan** [comment]
@Appkad, unfortunately, this is an issue specific to Teams and is not something the Bot Framework team can assist with.

You can file Teams bugs in the Teams [Uservoice](https://microsoftteams.uservoice.com/forums/908686-bug-reports) account.

**Comment by Appkad** [comment]
Thanks i post it in USerVoice.
