### ISSUE TITLE
ConversationResourceResponse.java json properties case problem

### ISSUE THREAD

**Issue by rmenkyna** [Microsoft/botbuilder-java#59]
Hello.
When we tried to create new conversation using java Library the function createConversation returned ConversationResourceResponse object without error but the id parameter was always null.  By debugging the code we have found that the MicrosoftBotFramework rest service result contained non null Id parameter. 
The problem is that Json annotations in ConversationResourceResponse are by default case sensitive.  So when MBF rest service returns parameters with names Id, ServiceUrl, ActivityId they are not properly deserialized into properties in ConversationResourceResponse class with these annotations. 
   @JsonProperty(value = "activityId")
   @JsonProperty(value = "serviceUrl")
   @JsonProperty(value = "id")

We were able to fix this behavior by using changed annotations
  @JsonProperty(value = "ActivityId")
  @JsonProperty(value = "ServiceUrl")
  @JsonProperty(value = "Id")

Please consider finding some solution for example: changing rest-response or changing Json annotations or configure deserializer to be case insensitive. etc...
Thank you.

**Comment by gcatanese** [comment]
Hi @rmenkyna , when creating a Conversation the REST API (according to documentation) only returns the ResourceResponse ID, hence you should only able to see the conversation id (created or re-used).

FYI I can get the conversation ID via the Java api without problems:

```
ConversationResourceResponse conversationResourceResponse = 
connector.conversations().createConversation(parameters); 
LOGGER.log(Level.INFO, "conversation.id {0}", conversationResourceResponse.id());
```
Hope it helps.

/Bep

**Comment by tdurnford** [comment]
By convention, the Microsoft BotFramework uses camel case when naming JSON properties, so the JSON Annotations should be camel case as well. `activityId` in the incoming JSON should map to `@JsonProperty(value = "activityId")` when the framework deserializes the incoming JSON into a ConversationResourceResponse object. 

When I run the Java BotFramework [Connector Tests](https://github.com/Microsoft/botbuilder-java/blob/ed0112498a838e83ca21ef9f4a07b432bf635f89/libraries/bot-connector/src/test/java/com/microsoft/bot/connector/ConversationsTest.java#L17), I am not seeing any issues regarding the activityId, and I'm not getting any errors when I run @gcatanese's code above.

```Java
@Test
public void CreateConversation() {

    Activity activity = new Activity()
            .withType(ActivityTypes.MESSAGE)
            .withRecipient(user)
            .withFrom(bot)
            .withText("TEST Create Conversation");

    ConversationParameters params = new ConversationParameters()
            .withMembers(Collections.singletonList(user))
            .withBot(bot)
            .withActivity(activity);

    ConversationResourceResponse result = connector.conversations().createConversation(params);
    Assert.assertNotNull(result.activityId());
}
```

**Comment by CoHealer** [comment]
Closing as not repro
