### ISSUE TITLE
[Teams] Fetching the team roster

### ISSUE THREAD

**Issue by gcatanese** [microsoft/botbuilder-java#60]
**Is your feature request related to a problem? Please describe.**

It is not currently possible to fetch the MSTeams Roster via the SDK.:

`GET /conversations/{teamId}/members/`

This is very useful to be able to initiate conversations with the MSTeams users

**Describe the solution you'd like**
Create a new implementation "Teams" to be able to fetch this information (similarly as it is possible to fetch ActivityMembers)

**Describe alternatives you've considered**
Presently I implement a HTTP GET (including author token) to fetch the list of members

**Additional context**
https://docs.microsoft.com/en-us/microsoftteams/platform/concepts/bots/bots-context

[enhancement]

**Comment by romankoval** [comment]
I would like to vote for this feature, such as it's very needed functionality to get users of recently added team.

**Comment by tracyboehrer** [comment]
Closed via PR
