### ISSUE TITLE
TeamInfo type does not expose aadGroupId (java)

### ISSUE THREAD

**Issue by gabog** [microsoft/botbuilder-java#605]
See [parent](https://github.com/microsoft/botframework-sdk/issues/5870)

**Comment by EricDahlvang** [comment]
Looks like this field already exists in the java sdk:

https://github.com/microsoft/botbuilder-java/blob/master/libraries/bot-schema/src/main/java/com/microsoft/bot/schema/teams/TeamInfo.java#L30

closing
