### ISSUE TITLE
Azure deployment does not create bot channel registration

### ISSUE THREAD

**Issue by EricZeiberg** [microsoft/botbuilder-java#644]
## Version
Latest version on GitHub

## Describe the bug
I followed the directions to deploy the [Echo Bot sample ](https://github.com/microsoft/botbuilder-java/tree/master/samples/02.echo-bot)to Azure and while the app builds and deploys as usual, it does not create a Bot Channel Registration as stated in the README. 

## To Reproduce
Follow README on the Echo Bot sample project

## Expected behavior
According to the README, the maven deployment should create a bot channel registration in addition to the app service. (Correct me if I'm wrong)

[bug]

**Comment by EricZeiberg** [comment]
Thanks for the help...

**Comment by tracyboehrer** [comment]
@EricZeiberg Apologies.  Accidental closure.

**Comment by tracyboehrer** [comment]
Are you deploying to a new or existing resource group?  I tested deploying to an existing group, and the correct Azure resources are created:

Bot Channel Registration
App Service
App Service Plan

These resources should be created in step #4 under "Deploy the bot to Azure".  To be clear, this step is prior to the Maven deploy step (which is just deploying the bot code in our case).

**Comment by EricZeiberg** [comment]
Just tried to rerun the `az group deployment` command and it worked this time. Must of made a typo when I initially ran the command, didn't realize that those resources were created at that step, vs step 7. 

Thanks for your help!
