### ISSUE TITLE
Unreleased Resource: Streams

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [microsoft/botbuilder-java#721]
https://github.com/microsoft/botbuilder-java/blob/5f345d5422d779d2afa6c07e1a0dc041b0eff073/samples/56.teams-file-upload/src/main/java/com/microsoft/bot/sample/teamsfileupload/TeamsFileUploadBot.java#L204
https://github.com/microsoft/botbuilder-java/blob/5f345d5422d779d2afa6c07e1a0dc041b0eff073/samples/56.teams-file-upload/src/main/java/com/microsoft/bot/sample/teamsfileupload/TeamsFileUploadBot.java#L246

The program can potentially fail to release a system resource.

**Comment by EricDahlvang** [comment]
@tracyboehrer  can you take a look at this please?
