### ISSUE TITLE
Skills Support

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-java#738]
- [x] connector: SkillsValidation
- [x] botbuilder: Skills namespace
- [x] dialogs
- [ ] Skills samples
  - [x] Simple
  - [ ] Dialog
- [ ] References/usage

**Comment by gabog** [comment]
Hi @tracyboehrer, was this added so we can address it in R11? if yes, should I assign it to you? 
Thanks

**Comment by tracyboehrer** [comment]
@gabog As far as I know we aren't adding it in R11.  Not sure why @clearab added it.  Java doesn't even have a dialog stack yet.

**Comment by gabog** [comment]
OK, I'll move it to the backlog then.

**Comment by clearab** [comment]
What did I add?
