### ISSUE TITLE
bot-dialogs package

### ISSUE THREAD

**Issue by tracyboehrer** [microsoft/botbuilder-java#743]
Requires microsoft.recognizers.text, which hasn't been released to Maven:  https://github.com/Microsoft/Recognizers-Text/tree/master/Java

The options are:
1) Manually clone and build the recognizers (Preview Only, but we'd have issues with PR's)
2) Configure Maven to use JitPack, which produces a package during the build by cloning and building behind the scene. It is free for open source projects.  (Preview Only)
3) Finalize and release recognizers (Required for GA)

**Comment by tracyboehrer** [comment]
See also https://github.com/microsoft/Recognizers-Text/issues/2254

**Comment by tracyboehrer** [comment]
Beginning of port: https://github.com/microsoft/botbuilder-java/tree/trboehre/dialog

**Comment by egorovpavel** [comment]
Hi @tracyboehrer. Any progress or eta on Bot-Dialogs implementation?  Thx.

**Comment by tracyboehrer** [comment]
@egorovpavel We haven't made anymore progress on the port that was started.  Realistically, we're probably looking at around the end of the 1st quarter 2021 before we can GA the Java SDK, which would include Dialog.

**Comment by egorovpavel** [comment]
@tracyboehrer thank you for feedback.

**Comment by tracyboehrer** [comment]
See #901

**Comment by LeeParrishMSFT** [comment]
Re-Opening since the OAuthPrompt hasn't yet been ported. We can close this again once that is completed.
