### ISSUE TITLE
Issue trying run samples like 02.echo-bot

### ISSUE THREAD

**Issue by denstren** [microsoft/botbuilder-java#929]
## Version
Preview 8

## Describe the bug
I am trying to run the samples like 02.echo-bot.
The echo bot starts up fine.
But, as soon as I send a message to the bot in the Teams app it throws the following error.

java.util.concurrent.CompletionException: java.io.IOException: java.util.concurrent.ExecutionException: com.microsoft.bot.connector.authentication.AuthenticationException: java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: com/nimbusds/oauth2/sdk/http/CommonContentTypes

Full startup and stack trace attached.
[02.echo-bot.stack.trace.txt](https://github.com/microsoft/botbuilder-java/files/5901551/02.echo-bot.stack.trace.txt)

I created an echo bot in Visual Studio using C# with the same App Id and Password and it worked as expected and echoed the message.

## To Reproduce
1. Start the 02.echo-bot.
2. Connect to the Bot via the Teams App and send a message.
3. It throws the error in the attached stack trace.

## Expected behavior
Should echo back the message in the Teams App.

## Additional context
Let me know if you need any more details.

**Comment by tracyboehrer** [comment]
@denstren It looks like Java MSAL has a new version that resolves a missing dependency related to nimbusds.

https://github.com/AzureAD/microsoft-authentication-library-for-java/releases/tag/v1.8.1

We get this corrected in the next preview, which is coming in a couple of weeks.

**Comment by denstren** [comment]
Thanks!  Updating to MSAL 1.8.1 worked.
