### ISSUE TITLE
Activity#entities fails to deserialise values from MSTeams

### ISSUE THREAD

**Issue by wilmol** [microsoft/botbuilder-java#98]
## Version
in my build.gradle:
"com.microsoft.bot.schema:botbuilder-schema:4.0.0-a1"
and
"com.microsoft.bot.connector:bot-connector:4.0.0-a1"

## Describe the bug
```Activity#entities``` field fails to be deserialised from microsoft teams.
I.e. the payload sends a List with a single element of type Map, only a single value from that map is deserialised ("clientinfo" which has key "type").
 
## To Reproduce
1. Create a bot using Java botbuilder SDK
2. Run bot in ms teams
3. Send a message
4. Observer your logs of Activity schema
5. Note that the JSON payload for entities is a ```List<Map>```
6. Note in your Java app only "clientinfo" is present

## Expected behavior
For the ```entities``` value to be deserialised properly.
Note it is a ```List<Entity>``` type (in ```Activity```). ```Entity``` defines a single field ```type```, but the payload sends a list of key value pairs (```LinkedHashMap```). So I expect ```Entity``` is suppose to define two fields ?? e.g. ```type``` and ```value```.

Current workaround is to extend the ```Activity``` class and define a field ```entities``` of type ```List<Map<String, String>>```. Then use the subclass as parameter in my ```@POST``` method instead of ```Activity```.

## Screenshots
JSON payload:
![Screen Shot 2019-08-27 at 9 10 29 AM](https://user-images.githubusercontent.com/18110897/63724259-75090900-c8ab-11e9-9475-cac552189def.png)

When my endpoint accepts ```com.microsoft.bot.schema.models.Activity```:
![Screen Shot 2019-08-27 at 9 14 55 AM](https://user-images.githubusercontent.com/18110897/63724265-7a665380-c8ab-11e9-9054-3d614d56bd9b.png)

When my endpoint accepts ```java.lang.Object``` (or my subclass):
![Screen Shot 2019-08-27 at 9 13 16 AM](https://user-images.githubusercontent.com/18110897/63724282-805c3480-c8ab-11e9-8fc2-e36b059b4c26.png)

## Additional context
This is similar to another issue I reported (https://github.com/microsoft/botframework-sdk/issues/5489). I was able to work around that issue by extending the ```Activity``` class too but would be nice for the sdk to support it officially. 

[bug]

**Comment by wilmol** [comment]
Sounds good, I will stick with the workaround for now.

**Comment by tracyboehrer** [comment]
Preview 2 notes for this issue:

bot-schema/connector uses Entity for the wire format (Activity.getEntities).  Since there are different types of entities, each with unique properties, Entity.getProperties can be used to access additional properties (see also Entity.getType).  Activity.getMentions can be used to get "mention" type entities in the form of a list of Mention objects.
